#!/usr/bin/env bash
# setup-email.sh — configure Resend email notifications
#
# Interactive:  ./setup-email.sh
# CLI args:     ./setup-email.sh --api-key re_XXXX --to you@example.com

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=common.sh
source "$SCRIPT_DIR/common.sh"

usage() {
    cat <<EOF
Usage: $(basename "$0") [OPTIONS]

Configure email notifications via Resend.

Options:
  --api-key KEY    Resend API key (starts with re_)
  --to EMAIL       Recipient email address
  -h, --help       Show this help

With no arguments, runs interactively.
EOF
    exit 0
}

# --- Parse args ---

API_KEY=""
TO=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --api-key) API_KEY="$2"; shift 2 ;;
        --to)      TO="$2"; shift 2 ;;
        -h|--help) usage ;;
        *) echo "Unknown option: $1"; usage ;;
    esac
done

# --- Interactive prompts if args missing ---

if [[ -z "$API_KEY" || -z "$TO" ]]; then
    echo "=== Mac House Keep — Email Setup ==="
    echo ""
    echo "This will configure email notifications using Resend (https://resend.com)."
    echo "You'll need a free Resend API key and the email address to receive alerts."
    echo ""
fi

if [[ -z "$API_KEY" ]]; then
    read -rp "Resend API key: " API_KEY
fi

if [[ -z "$TO" ]]; then
    read -rp "Recipient email: " TO
fi

# --- Validate ---

if [[ ! "$API_KEY" =~ ^re_ ]]; then
    echo "Error: API key must start with 're_'."
    exit 1
fi

if [[ ! "$TO" =~ @ ]]; then
    echo "Error: '$TO' doesn't look like a valid email address."
    exit 1
fi

# --- Write config ---

mkdir -p "$CONFIG_DIR"
cat > "$CONFIG_FILE" <<EOF
# Mac House Keep email config (auto-generated by setup-email.sh)
RESEND_API_KEY="$API_KEY"
TO_EMAIL="$TO"
EOF

log "Email config written to $CONFIG_FILE"

# --- Send test email ---

load_config

log "Sending test email to $TO_EMAIL..."

send_email \
    "Mac House Keep — Test Email" \
    "If you're reading this, email notifications are working correctly."

echo ""
echo "Done! Email config saved to config/email.conf"
echo "You can re-run this script at any time to update settings."
